# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aVox3i5VyMnBk0pFXlnIN8NP0kiqMEfm
"""

import os

def search_files(start_path, search_name):
    """Search for files or folders in a given directory and its subdirectories."""
    matches = []
    for root, dirs, files in os.walk(start_path):
        if search_name in dirs:
            matches.append(os.path.join(root, search_name))
        if search_name in files:
            matches.append(os.path.join(root, search_name))
    return matches

if __name__ == "__main__":
    start_directory = input("Enter the directory to start search: ")
    search_query = input("Enter the file or folder name to search: ")

    results = search_files(start_directory, search_query)

    print("Found:") if results else print("No matches found.")
    for result in results:
        print(result)

